# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 748c70afee351135ea25e0b8a994fdd0edf3cf04bc4ba9cd34adfe01abde2bdca5b6a30156d0dff37022ba3b1bcd968d5e2c75bbef9438a4e28d1b3cae6c30c9

test:
  secret_key_base: a6e473724ecadc0fd65fdc5a516f3725bd9f83d504ef4cf21bb72e9b13d56ab7c66c78e6ae15c10b29135b55fce49913540c51fdc33cf1de8994ecc548af5f95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
